export const IPC_CHANNELS = {
  importPreview: 'import.preview',
  importApply: 'import.apply',
  importExcel: 'import.excel',
  diffGet: 'diff.get',
  ganttQuery: 'gantt.query',
  schedulesList: 'schedules.list',
  schedulesCreate: 'schedules.create',
  schedulesUpdate: 'schedules.update',
  schedulesDelete: 'schedules.delete',
  importsList: 'imports.list',
  viewsList: 'views.list',
  viewsSave: 'views.save',
  exportCsv: 'export.csv',
  exportXlsx: 'export.xlsx',
  exportJson: 'export.json',
  taskUpdate: 'task.update',
  historyUndo: 'history.undo',
  historyRedo: 'history.redo',
  historyStatus: 'history.status',
  contextMenuTask: 'context-menu.task',
  menuAction: 'menu.action'
} as const;
